### ISSUE TITLE
How to submit stream task use jdbc driver

### ISSUE THREAD

**Issue by 22221cjp** [ververica/flink-jdbc-driver#5]
RT，thanks

**Comment by godfreyhe** [comment]
Currently, jdbc driver only supports submit batch job, because stream job will be endless, we can't get the job result as batch.

btw, can you explain more about what do want about jdbc driver ? just submit streaming insert statement, or do some streaming select ?

**Comment by 22221cjp** [comment]
I want to submit the SQL stream task through the REST API or JDBC driver, just like the command-line submission of "Flink SQL client embedded". For example, create source tables, create views, create result tables, execute queries, insert result tables, etc. It's better to be able to submit multiple SQL statements separated by semicolons one at a time, like the following code. How can i do ?

create table source_table (
   a varchar,
   b varchar
) with (
   xx
);

create table result_sink (
  c varchar,
  d  varchar
) with (
	yy
);
create view temp_view as 
select * from source_table;

insert into result_sink
select * from temp_view;

**Comment by godfreyhe** [comment]
thanks for sharing the details, sql-gateway supports REST API (which is also unique entry point). We are working on the documentation and will release it soon. `multiline statements supporting` is also under developing.

Any contribution is welcome~

**Comment by 22221cjp** [comment]
So, "sql-gateway" support the submission of SQL stream task through REST API?

**Comment by godfreyhe** [comment]
yes, You can refer to [FLIP-91 design document](https://docs.google.com/document/d/1DKpFdov1o_ObvrCmU-5xi-VrT6nR2gxq-BbswSSI9j8/edit?ts=5e4cd711#) for more details, the REST APIs are almost same.

**Comment by 22221cjp** [comment]
OK, thanks a lot!
